### ISSUE TITLE
landing page: press enter to submit things too

### ISSUE THREAD

**Issue by digonsan** [JamesPKIV/Purposeful#87]
Relevant files:
LandingPage.js
LandingPage.css (maybe)

Description:
Right now the only way to continue, sign up, and log in, is by actually pressing the buttons to submit our input. We should try to make it so that if the user presses enter in their keyboard it also logs them in.
 
BONUS (imaginary) points: go through all the components that have forms (landing page, edit profile, etc.) and make it so that the cursor is ready to start typing at the first entry (so user doesn't have to click on it).

**Comment by ogparra** [comment]
Working on it!

**Comment by ogparra** [comment]
Finished the first task. Will be working on BONUS after I see what else needs to be done.

**Comment by digonsan** [comment]
Hey Oscar I found a way to do the "BONUS" while I was doing other stuff so I went ahead and did it.... So I am gonna close this issue ok?
